name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 29.4
    - uses: actions/checkout@v4
    - name: Run tests
      run: make package-lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 24.3
          - 25.3
          - 26.3
          - 27.2
          - 28.2
          - 29.4
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v4
    - name: Compile
      run: make compile
